### ISSUE TITLE
Ability to use attributes other than name for building the json

### ISSUE THREAD

**Issue by 91Seconds** [marioizquierdo/jquery.serializeJSON#113]
I'm developing a flask app with WTForms where the name attribute on fields is set by the python variable name used to store the field on creation of the form.  For example, the python code
`field1 = DecimalFeild()`
creates 
`<input name="field1" type="number">`

This effectively makes the name attribute reserved but I can pass any other attribute like:
`feild1 = DecimalFeild(render_kw={'json_name': 'object[fieild1]'})`
which creates
`<input name="field1" json_name="object[fieild1]" type="number">`

I'd love to be able to use this code you've written but with custom attributes

**Comment by marioizquierdo** [comment]
The current code builds on top of [jQuery serializeArray](https://api.jquery.com/serializeArray/), which only works with `name` attributes, using the standard W3C rules for successful controls to determine which elements it should include.

If we wanted to change that, we would have to stop depending on serializeArray, and write our own code that is equivalent, and also allows for more customization. When the plugin was first written, I was opposed to doing that in order to keep the plugin simple and predictable, but giving its success, I would be open to such rewrite; thankfully the plugin has extensive tests to verify that it works as expected. But I don't think I will be able to embark in this task anytime soon.

**Comment by 91Seconds** [comment]
Thanks for the reply.  It's not pretty but WTForms can be made to custom `name` attributes so that's what I have done and it is working with your code.  Thank you for writing this library.

**Comment by yurikus** [comment]
This might be revisited with an option to supply attr to use instead of `name` in light of v3.2.0 taking over serializeArray from jQuery.
