### ISSUE TITLE
It doesn't serialize type=file

### ISSUE THREAD

**Issue by bahmansh** [marioizquierdo/jquery.serializeJSON#122]
Please add it.
thanks.

**Comment by marioizquierdo** [comment]
?

**Comment by bahmansh** [comment]
what is your question?

I said that when form contains <input type="file" name="file1"/>, jsonSerialize can not serialize it. How can I do it?

**Comment by marioizquierdo** [comment]
Ah, I think with `type=file` you mean `<input type="file">`?

This plugin doesn't support data types. [JQuery's serializeArray](https://api.jquery.com/serializearray/) (the base serialization method this plugin is based of) also doesn't support data types. That is because the W3C rules for [successful controls](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.2) determine that data from file select elements should not be serialized.

In practice, you browser's JavaScript is not allowed to read contents from files. This is for security, otherwise any website could silently upload contents of your file system into their website. If you want to control file uploads from JavaScript, you have other options. Some resources for you: [Javascript upload file](https://stackoverflow.com/questions/5587973/javascript-upload-file), [file upload with jquery](https://stackoverflow.com/questions/4545081/how-to-do-file-upload-using-jquery-serialization), [serialize file input](https://www.sitepoint.com/community/t/jquery-how-do-i-serialize-file-type-input-in-jquery/6392).

Good luck!
