### ISSUE TITLE
switching from SerializeObject

### ISSUE THREAD

**Issue by derekriebau** [marioizquierdo/jquery.serializeJSON#30]
I'm switching from using this code (https://github.com/hongymagic/jQuery.serializeObject) to using your serializeJSON instead. In both cases, I'm trying to send JSON to a java backend. My application was developed with the SerializeObject in mind, but I'd like to switch over to using your code here.

Can you see any reason why SerializeJSON would produce a different data structure than SerializeObject? I'm comparing the outputs of [ form -> SerializeObject ] vs. [ form -> serializeJSON -> JSON.stringify ]. I feel stumped.

**Comment by marioizquierdo** [comment]
`serializeObjet` and `serializeJSON` do not follow the same format.

`serializeJSON` uses the same format as the default Ruby on Rails request params hash, which it's widely used and works very well.

On top of that, `serializeJSON` has many options that can modify slightly how the output is parsed (i.e. understand booleans, numbers and nulls instead of always rendering a string), but the idea is to keep the default behavior simple and predictable.

If you want to migrate, you will have to change the input names to match the expected format (aka: append "[]" if you want to make a list)
