### ISSUE TITLE
File attachement

### ISSUE THREAD

**Issue by gogliko** [marioizquierdo/jquery.serializeJSON#36]
i use jquary serializeJson ,but i have one troulbe i can't post File how i can do this ? 

my code 

  var courseType = $('#main-form').serializeJSON();
  

        $.post("/course/types/save",
            courseType, function(data){}

form action="#" class="form-horizontal" id="main-form" enctype="multipart/form-data">

input type="file" name="photo" 

form

**Comment by guitsaru** [comment]
This is probably outside the scope of this project, but you can read the file in using javascript: http://www.html5rocks.com/en/tutorials/file/dndfiles/

**Comment by marioizquierdo** [comment]
Files are not supported by this plugin, as they are not supported by jQuery `serializeArray`.

Your problem is with JavaScript and browsers in general. Here you have a few more resources to deal with it:

  * http://stackoverflow.com/questions/5513485/form-serialize-workaround-for-file-fields
  * http://stackoverflow.com/questions/4545081/how-to-do-file-upload-using-jquery-serialization
  * http://blog.teamtreehouse.com/uploading-files-ajax
