### ISSUE TITLE
Bug with <select multiple>

### ISSUE THREAD

**Issue by avnovoselov** [marioizquierdo/jquery.serializeJSON#38]
I got a bug with select "multiple" attr
```html
<form>
    <select name="city" multiple>
        <option></option>
        <option value="1" selected>NY</option>
        <option value="2" selected>London</option>
        <option value="3">Tokyo</option>
    </select>
</form>
```

```javascript
var data = $('form').serializeJSON();
// > data = {city: "2"}
```
imho, ```{city: ["1", "2"]}``` would be right

UPD: but
```html
<form>
    <select name="city[]" multiple>
        <option></option>
        <option value="1" selected>NY</option>
        <option value="2" selected>London</option>
        <option value="3">Tokyo</option>
    </select>
</form>
```
works ok

**Comment by marioizquierdo** [comment]
It's expected behavior.
I know it's a little confusing, but it's important that serializeJSON behaves exactly as Ruby Rack (see [parse_nested_query](http://codefol.io/posts/How-Does-Rack-Parse-Query-Params-With-parse-nested-query) explanation) when the params are sent by a regular HTML form. This ensures compatibility and robustness. Also, the other way around would also be confusing and it would create problems in some other scenarios.

Think about it: the tag names are not coupled to the type (input textfield vs select vs select-multiple). If you name it `city` then it's supposed to be a single value (each option will replace the value, thus the last option will be what it's shown in the serialized object). If you name it `city[]` then it's supposed to be an array (each selected option will be added to the array).
