### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by okwei2000** [marioizquierdo/jquery.serializeJSON#39]
Is it possible to define the type of the form fields in the attribute (e.g. data-type="number") instead of put it part of the name of the field? It's much easier to populate data back to the form, and it will work better with other libs?

**Comment by marioizquierdo** [comment]
I know, it would be better for the interface definition.. but the implementation would be more "risky".
The reason I added the types as part of the input name in the first place, is because the implementation relies on jQuery `serializeArray`, that only knows about input names and values (checkboxes, textareas and whatnot) using the exact same extraction rules as any standard HTML form.
If `serializeJSON` needs info from the data attributes, then it can not rely on `serializeArray` anymore, risking the stability and compatibility of the library (we would have to implement a serializeArray ourselves, being very careful when it comes to edge cases and W3C standards).

And, once there is type checking, the form values are not standard anymore.
In order to do easily populate data back to the form, I think it's best to just don't use types, and do the type conversion after the form is serialized. Assuming all fields are Strings is best for compatibility.

**Comment by okwei2000** [comment]
I'm using a little util function to populate data back to the form by
checking the type of the json value and concatenating the type to the name
of the field.
