### ISSUE TITLE
array with object notation overwriting previous array entries

### ISSUE THREAD

**Issue by ARolek** [marioizquierdo/jquery.serializeJSON#41]
I'm having problems getting the array and objection notation to work together. I have put together the following jsfiddle to represent the situation: https://jsfiddle.net/9kurm7qz/15/

If I remove the nested object nation, everything will be pushed into an array fine. If I keep the object notation after the array notation, only the last entry is created. It might be my syntax, but I can't seem to figure out where the issue is.

**Comment by marioizquierdo** [comment]
Your issue is the same as the common "unchecked checkboxes" and "select multiple" problems, where subsequent values will just "replace" the previous value.

What's going on in your case, is that all your input names are the same, so, by definition they "replace" the same value.

You should add an index (0,1,2,..) to specify what element they are, so the input names are different:

```html
    <input name="wiki[0][size][min]" value="100"/>
    <input name="wiki[1][size][min]" value="200"/>
    <input name="wiki[2][size][min]" value="300"/>
```

Note that this will create an object instead of an array `{"0": {"size": {"min": 100}, "1": ...}}}`. If you want the array, you should use the `useIntKeysAsArrayIndex` option (see README file).

Another option for you, would be to use a hidden field to "push" an empty object into the array, before inserting the value you want:

```html
    <input type="hidden" name="wiki[]:object" value='{}' />
    <input name="wiki[][size][min]" value="100"/>
    
    <input type="hidden" name="wiki[]:object" value='{}' />
    <input name="wiki[][size][min]" value="200"/>

    <input type="hidden" name="wiki[]:object" value='{}' />
    <input name="wiki[][size][min]" value="300"/>
```
See [fiddle for this example](https://jsfiddle.net/9kurm7qz/17/).

But in this case you are using types and also repeating the same input name multiple tiles, which is "less standard".

**Comment by ARolek** [comment]
Thanks for the reply. Your hidden field hack is accomplishing what I'm looking for. Much appreciated, and thanks for the great lib.
