### ISSUE TITLE
Option to parse only non-text fields

### ISSUE THREAD

**Issue by rmehlinger** [marioizquierdo/jquery.serializeJSON#48]
So frequently, the fields we wish to parse are actually number fields, checkboxes, or radio buttons--maybe selects. But we don't want to parse, say, a plain text field just because the user happened to enter a number. An option to specify what input types you would like parsed would be very helpful. I'd be glad to help implement this.

**Comment by marioizquierdo** [comment]
Targeting what inputs to parse and how is done via jQuery selector. You could just do something like this:

```javascript
$('input[type=number]').serializeJSON({parseNumbers: true});
```

Otherwise, you can target what type to parse on each input by using `:types` (i.e. name your input `bananas:number` instead of just `bananas`).

If what you need is validation to make sure the user doesn't enter anything that is not a number, that should be done before serializing. Note that validation is not the responsibility of this plugin, and validation could be as simple as showing an alert on input change, to a complex jQuery plugin like [jqueryvalidation](http://jqueryvalidation.org/documentation/).
