### ISSUE TITLE
Ability to read disabled input values

### ISSUE THREAD

**Issue by josephj** [marioizquierdo/jquery.serializeJSON#49]
I'm very happy to find this library. It really helps me to solve the unchecked checkbox issues. 

However, It seems it doesn't have an option to read disabled input values. Any ideas or suggestions?

**Comment by marioizquierdo** [comment]
Yup, we don't have that.

While the default behavior needs to skip all the disabled fields, an option to include them would be nice (i.e. `includeDisabledFields: true`).

The problem is the same as with the unchecked checkboxes, since `jQuery.serializeArray` does not include any disabled field, we would have to manually select and include them in the serialized output.

As for now, I guess a workaround would be to enable the fields before serializing, and then disable them back, for example:

```javascript
function serializeJSONIncludingDisabledFields($form) {
  var $disabledFields = $form.find('[disabled]');
  $disabledFields.prop('disabled', true);
  $form.serializeJSON();
  $disabledFields.prop('disabled', false);
}
```

**Comment by josephj** [comment]
Thanks. The workaround solves my problem :)

**Comment by outaTiME** [comment]
Hi guys, the disable prop are inverted ... here solved version:

```js
serializeJSONIncludingDisabledFields: function (form) {
  var fields = form.find('[disabled]');
  fields.prop('disabled', false);
  var json = form.serializeJSON();
  fields.prop('disabled', true);
  return json;
}
```

Why this issue are closed ?? wontfix ?? 

thks !!

**Comment by marioizquierdo** [comment]
@outaTiME yes, it's a wontfix, since it's expected behavior by default.

I understand having an option like `{includeDisabledFields: true}` would be nice, but the workaround works well for most cases.

Thank you for pointing out that the disabled prop were inverted. I updated the first answer to correct that.
