### ISSUE TITLE
"select multiple options, just name it as an array[]" is not worling for me

### ISSUE THREAD

**Issue by MarioVanDenEijnde** [marioizquierdo/jquery.serializeJSON#60]
Hello marioizquierdo,

Apart from the fact that adding the brackets in the name is not very suitable for me it also is not working.
When I include "multiple" in the select tag the tag is not included in the element array. If I put [] after the name or not.

Is there another option to get a multiple select element included?

Kind regards,
Mario

**Comment by MarioVanDenEijnde** [comment]
Sorry. Forgot to mention "many thanks" for the script.

**Comment by marioizquierdo** [comment]
I think the problem may be somewhere else. Please make sure of the following:

  * Maybe the input is not properly matched by the jQuery selector?
  * Is it disabled?
  * Does it have a name attribute?

Note that serializeJSON will only serialize inputs that are supported by jQuery `.serializeArray()`, that uses the standard [W3C rules for successful controls](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.2) to determine which elements it should include. In particular, the included elements cannot be disabled and must contain a name attribute. No submit button value is serialized since the form was not submitted using a button. And data from file select elements is not serialized.

If you are still not sure, please provide a complete example (html + javascript) so I can see what part is being confusing.

Thanks!

**Comment by marioizquierdo** [comment]
@MarioVanDenEijnde I'm closing the issue because there was no follow up.
