### ISSUE TITLE
Checked checkbox value on

### ISSUE THREAD

**Issue by replay111** [marioizquierdo/jquery.serializeJSON#70]
Hi,

it seems that checked value via interface is reported as "on" not true:

```html
<form class="form-horizontal" id="formAddNewDictionary">
    <div class="form-group">
        <label for="edtCode" class="col-md-3 control-label">Kod słownika</label>
        <div class="col-md-9">
            <input type="text" class="form-control" id="edtCode" name="edtCode" placeholder="Kod" value="">
        </div>
    </div>
    <div class="form-group">
        <label for="edtDesc" class="col-md-3 control-label">Opis</label>
        <div class="col-md-9">
            <input type="text" class="form-control" id="edtDesc" name="edtDesc" placeholder="Opis" value="">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
            <div class="checkbox">
                <label>  <input name="chkVisible" id="chkVisible" type="checkbox"> Visible  </label>
            </div>
        </div>
        <div class="col-md-offset-3 col-md-9">
            <div class="checkbox">
                <label> <input name="chkEditable" id="chkEditable" type="checkbox"> Editable  </label>
            </div>
        </div>
    </div>
</form>
```

When I've clicked on interface "Visible" and call JS:

```$("#formAddNewDictionary").serializeJSON({checkboxUncheckedValue: "false"});```

I was given a result:

```Object {edtCode: "", edtDesc: "", chkVisible: "on", chkEditable: "false"}```

I was expecting on clicked checkbox true/false value :(

**Comment by marioizquierdo** [comment]
HTML checkboxes are confusing, I know. Please read the serializeJSON README in the section for unchecked checkboxes: https://github.com/marioizquierdo/jquery.serializeJSON#include-unchecked-checkboxes

HTML checkboxes are serialized with their "value" attribute if checked (I guess since you don't specify any value here, the browser may be using "on" by default). And they are NOT serialized at all if they are not checked.

For the boolean value, note that `serializeJSON` serializes all values as *strings* by default. The `checkboxUncheckedValue` specifies the *string* value that should be used if the checkbox is unchecked. If you want a boolean, you should use the `types` feature.

You could set their types to `:boolean` and use the `data-unchecked-value` attribute.
```html
  <input type="checkbox" name="chkVisible:boolean" value="true" data-unchecked-value="false"/>
  <input type="checkbox" name="chkEditable:boolean" value="true" data-unchecked-value="false"/>
```
Then serialize with no options:
```javascript
$("#formAddNewDictionary").serializeJSON();
```

If you want full HTML compatibility, you can use hidden fields, and just auto-parse boolean fields in your form:
```html
  <input type="hidden" name="chkVisible" value="false" />
  <input type="checkbox" name="chkVisible" value="true" />

  <input type="hidden" name="chkEditable" value="false" />
  <input type="checkbox" name="chkEditable" value="true" />
```
Then serialize with parseBooleans:
```javascript
$("#formAddNewDictionary").serializeJSON({parseBooleans: true});
```

You actually have quite a few options.

**Comment by replay111** [comment]
Thnx  this:

```html
<input type="checkbox" name="chkVisible:boolean" value="true" data-unchecked-value="false"/> 
```

works fantastic!
