### ISSUE TITLE
Deserialize JSON into form

### ISSUE THREAD

**Issue by koder217** [marioizquierdo/jquery.serializeJSON#71]
Hi,

Your plugin is very useful. However, it's only helpful in getting json from Form. Is there a way I can deserialize json and load it into the form i.e, setting the form with a JSON object ?

That would be extremely useful.

**Comment by marioizquierdo** [comment]
Sorry, this plugin doesn't deserialize.

The reason is that doing all the inverse operations, supporting all the options is quite difficult, it would add too much complexity to the plugin for "little gain".

In the other hand, it is very easy to do manually with plain jQuery, just assign the values. There are some [recommendations in StackOverflow](http://stackoverflow.com/questions/7298364/using-jquery-and-json-to-populate-forms) and I found a plugins that may work for you: [jquery.forms.populator](https://github.com/joeycaughey/jquery.forms.populator).

However I still recommend just doing it manually, for example, with this data:
```javascript
var data = {
  user: {
    firstName: "John",
    lastName: "Doe"
  },
  isCool: true
};
```

You can make a function to fillValues:
```javascript
// Fill form where input names follow the serializeJSON format.
var fillForm($form, data) {
  $form.find('[name="user[firstName]]"').val(data["user"]["firstName"]);
  $form.find('[name="user[lastName]]"').val(data["user"]["lastName"]);

  $form.find('[name="isCool"]').prop("checked", data["isCool"]); // checkbox with a bool value
}
```

Then just populate the form like this:
```javascript
var $form = $("#myform");
fillForm($form, data);
```
