### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by invisime** [marioizquierdo/jquery.serializeJSON#73]

**Comment by marioizquierdo** [comment]
Is this not a license? https://github.com/marioizquierdo/jquery.serializeJSON/blob/master/jquery.serializejson.js#L6-L8

**Comment by invisime** [comment]
Not really, no. It's not a license, it's a reference to several licenses. It's not unambiguous. For instance, are you intending this project to be licensed under GPL 2.0, or 3.0? Furthermore, there's a pretty big difference between the GPL and MIT licenses. Additionally, the source file you linked and the bower.json files indicate two different licenses: MIT only, and dual licensing respectively. It's pretty unclear as to whether software using this package must also be open sourced.

I believe that if you included the text of the license(s) you intend to use in a customary LICENSE.txt file, it would eliminate these possible sources confusion.

**Comment by marioizquierdo** [comment]
I added a MIT LICENSE.txt file. Thanks!

**Comment by Zach8777** [comment]
Hello Mario, I'm currently handling a software copyright infringement case. The judge has questioned our project's use of this file and believes that it is licensed under the GPL, which could potentially infect the entire project. I noticed that you have declared a Dual License in [the code comments](https://github.com/marioizquierdo/jquery.serializeJSON/blob/master/jquery.serializejson.js#L6-L8), but have only included a separate MIT license.txt. Therefore, I would like to confirm the actual license of this file and whether there is any contagious effect due to its declaration of the GPL. Does the 'Adding MIT license' commit means that this project will use only MIT license and deprecate GPL?
