### ISSUE TITLE
serializeJSON always return an jsonObject,but i except a jsonArray

### ISSUE THREAD

**Issue by wamdy** [marioizquierdo/jquery.serializeJSON#81]
serializeJSON always return an jsonObject,but i except a jsonArray,
form like this
```

<form id="myform">
    <input name="personname" value="1">
    <input name="personname" value="2">
    <input name="personname" value="3">
</form>

```

`$("#myform").serializeJson() `
will return 
`{personname:"3"} `
but i want 
`[{personname:"1"},{personname:"2"},{personname:"3"}]`
is there anyhelp?

**Comment by marioizquierdo** [comment]
If you have multiple inputs with the same name, they all collapse into the same field. That is exactly how it is supposed to work.

With serializeJSON you can use special notation to make them an array `personname[]`, for example:
```html
<form id="myform">
    <input name="personname[]" value="1">
    <input name="personname[]" value="2">
    <input name="personname[]" value="3">
</form>
```
```javascript
$("#myform").serializeJson();
//=> {personname: ["1", "2", "3"]}
```

The exact value you want is not possible, because serializeJSON never returns an array. You can however make a field which value is an array, for example:
```html
<form id="myform">
    <input name="people[0]personname" value="1">
    <input name="people[1]personname" value="2">
    <input name="people[2]personname" value="3">
</form>
```

```javascript
$("#myform").serializeJson({useIntKeysAsArrayIndex: true});
//=> {people: [{personname: "1"}, {personname: "2"}, {personname: "3"}]}
```
From this object you can get the "people" value to have your array.
