### ISSUE TITLE
Serializing nested attributes in subset of array not supported

### ISSUE THREAD

**Issue by keyboardsamurai** [marioizquierdo/jquery.serializeJSON#82]
I am using useIntKeysAsArrayIndex and would like to serialize a repeating range of input forms that would define multiple items inside a list. 

What I do is, I set up the input element like so

```
<input name="items[0].vendor" value="Honda">
<input name="items[0].modelName" value="Goldwing">
<input name="items[1].vendor" value="Yamaha">
<input name="items[1].modelName" value="CBR">
```
When I run `JSON.stringify($('form').serializeJSON({useIntKeysAsArrayIndex: true}));` I get

```
{
  ...,
  "items": {
    "0.vendor": "Honda",
    "0.modelName": "Goldwing",
    "1.vendor": "Yamaha",
    "1.modelName": "CBR",

  }
}
```

What I really would have liked is this:

```
{
  ...,
  "items": [
  	{"vendor":"Honda","modelName":"Goldwing"},
  	{"vendor":"Yamaha","modelName":"CBR"}
  ]
}
```
Is something like this not supported? Is there a way to amend it?

**Comment by keyboardsamurai** [comment]
Upon studiying the docs again I found `<input name="items[0][vendor]" value="Honda">` to be a valid workaround. However, since my html generator is thymeleaf and the defaults are as described above, it would be very convenient if it would work out of the box.

**Comment by marioizquierdo** [comment]
Interesting proposal. Key names like `items[0].vendor` are not defined in the current syntax. The plugin should probably error with keys like that, instead of generating incongruent keys.

Since the behavior with dot syntax is not defined, I think it would be OK to add support for it on a new update. However I'm not sure if the change will be simple enough, I don't want to add too much complexity to the plugin and test cases. I'll think about it whenever I have some free time. If you can propose a PR with test cases it will speed up the process ;)

**Comment by keyboardsamurai** [comment]
I see what you mean, I already tried to hack this into the existing code. It seemed to be too much work though. FWIW I just went with the regular syntax, overriding the defaults. I'll just close this issue, since I believe you are probably very much justified in not wanting to add unnecessary complexity to this plugin. Thank you for considering it, though.
