### ISSUE TITLE
Array of nested object doesn't seem to work 

### ISSUE THREAD

**Issue by joandvgv** [marioizquierdo/jquery.serializeJSON#92]
I have an issue which is driving me crazy because this was working before and I don't know how.

I have these two input names: 
```
name="co-applicants[][personal-details][name] value="Elena"
name="co-applicants[][personal-details][name] value="Jesus"
```

And I expect this output:
```json
{"co-applicants": [
  {"personal-details": { "name": "Elena" }},
  { "personal-details": { "name:" "Jesus" }}
]}
```

However, it only produces this:
```json
{"co-applicants": [
  { "personal-details": { "name": "Jesus" }}
]}
```

It seems like it's ignoring first array element.
What should I do about it?

**Comment by marioizquierdo** [comment]
That is because the key is 2 levels deep, then it behaves like a regular object, the last value overrides.

Example:
```html
<form>
  <input type="text" name="personal-details[name] value="Elena" />
  <input type="text" name="personal-details[name] value ="Jesus" />
</form>
```

```js
$('form').serializeJSON();
// returns =>
{ "personal-details": { "name": "Jesus" }}
```

If you use `[]` to define array items, and they have a nested key, serializeJSON decides that you want multiple objects. For example:
```html
<form>
  <input type="text" name="co-applicants[][name] value="Elena" />
  <input type="text" name="co-applicants[][name] value ="Jesus" />
</form>
```

```js
$('form').serializeJSON();
// returns =>
{"co-applicants": [{"name": "Elena"}, {"name": "Jesus"}]}
```

But if you use 2 levels deep (`[][personal-details][name]`), then the serializer has no way to know if you mean to create a new object or modify the existing attribute, and uses the latter to be consistent with regular object behavior.

### Solution: use indexes

The solution to this (and many other array-related issues) is to explicitly use indexes. Use `[0]`, `[1]`, and the option `useIntKeysAsArrayIndex: true`:

```html
<form>
  <input type="text" name="co-applicants[0][personal-details][name] value="Elena" />
  <input type="text" name="co-applicants[1][personal-details][name] value="Jesus" />
</form>
```

```js
$('form').serializeJSON({useIntKeysAsArrayIndex: true});
// returns =>
{"co-applicants": [
  {"personal-details": { "name": "Elena" }},
  { "personal-details": { "name:" "Jesus" }}
]}
```


 adding object keys to an array will create new objects, but having multiple levels deep
